use_frameworks!

platform :ios, '10.0'

target 'CCIAPManager_Example' do
  pod 'CCIAPManager', :path => '../'

  target 'CCIAPManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
